sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tomen-coder/pfswcho_zad1:test -f ./home/Dockerfile.dev ./home

script:
  - docker run -e CI=true tomen-coder/pfswcho_zad1:test npm run build

after_success:
  - docker build -t tomen-coder/pfswcho_zad1:fib-home ./home
  - docker build -t tomen-coder/pfswcho_zad1:fib-server ./server
  - docker build -t tomen-coder/pfswcho_zad1:fib-documentation ./documentation
  - docker build -t tomen-coder/pfswcho_zad1:fib-calculator ./calculator
  # Logowanie do docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push obrazow do docker hub
  - docker push tomen-coder/pfswcho_zad1:fib-home
  - docker push tomen-coder/pfswcho_zad1:fib-server
  - docker push tomen-coder/pfswcho_zad1:fib-documentation
  - docker push tomen-coder/pfswcho_zad1:fib-calculator
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "pfswchozad-111"
  env: "pfswchozad111-env"
  bucket_name: "elasticbeanstalk-eu-north-1-539708463733"
  bucket_path: "pfswchozad-111"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
